language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
  - jruby
script: bundle exec rspec spec

gemfile:
  - gemfiles/Gemfile.activerecord-4.2.x
  - gemfiles/Gemfile.activerecord-5.1.x
  - gemfiles/Gemfile.activerecord-5.2.x
  - gemfiles/Gemfile.basic

matrix:
  exclude:
    - rvm: jruby
      gemfile: gemfiles/Gemfile.activerecord-4.2.x
